### ISSUE TITLE
RFE - Include Percentage loss feature in Bench-Iperf

### ISSUE THREAD

**Issue by pradiptapks** [perftool-incubator/bench-iperf#19]
The 0-drop hunter patch [1] has an inconsitency in the UDP packet while increasing the length size by more than 1K (reference issue [2]). 

To find consistency in the multiple samples results, the binary-search mechanism of `bench-iperf` needs further condition check to accept minimal percentage drop (as per RFC loss standard). 

The feature will help full to get more granular result `bench-iperf` benchmarking.

1.  Git branch
  ```
 # git remote -v; git branch
    origin  https://github.com/HughNhan/bench-iperf (fetch)
    origin  https://github.com/HughNhan/bench-iperf (push)
    * (HEAD detached at origin/zero-drop-hunter)
```

2. https://github.com/perftool-incubator/bench-iperf/issues/18

**Comment by HughNhan** [comment]
This was a goal per Issue #13

**Comment by HughNhan** [comment]
DUP request
