### ISSUE TITLE
test length handling

### ISSUE THREAD

**Issue by k-rister** [perftool-incubator/bench-iperf#9]
The https://github.com/perftool-incubator/bench-iperf/blob/main/iperf-get-runtime script needs to be switched from `duration` to `time` for proper run length reporting.

However, it seems like the `time` parameter isn't always to be trusted?

https://github.com/perftool-incubator/bench-iperf/blob/main/iperf-client#L192-L200

Why would we let a pass through argument override a core parameter that we use for managing the run?

**Comment by HughNhan** [comment]
I over looked the use of iperf-get-runtime.  Will fix soon.

As for the passthru params overriding explicit params behavior, it is by intention. The rational being, iperf3 provides a lot of non-essential options that we do not validate all. By allowing the passthru mode, we leave the door open for quick **experiments** using those non-essential options. [README](https://github.com/perftool-incubator/crucible-examples/tree/main/iperf) has the disclaimer for this subject.  Typically in the mv-params.json, the --time param is in the common section. The passthu test most likely is in a separate json block. So time params conflict will be the most likely case. And, if there is a conflict, passthru params should prevail.

**Comment by k-rister** [comment]
I understand the need to allow pass through parameters for experimentation, but doing so with the time parameter is going to be very problematic -- it will almost certainly break Crucible at some point (when the passed through value is greater than the parameter value).  I would make a rule that pass through should never be used for time specifically.

**Comment by HughNhan** [comment]
The plan is passthru is not allowed to commit.

**Comment by k-rister** [comment]
I'm not quite sure what that means, what do you mean by "commit"?

This has the potential to break an individual run -- the roadblock timeout(s) are constructed using the expected runtime of the workload.  So if you set a time length via pass through that is longer than what time is set to (or the default value for time) the run is going to break (meaning hit a timeout error and fail) because you have code that is explicitly telling it to use the pass through value instead of the actual time parameter.  The only way it will work to have a pass through time parameter is to also set the time parameter and the pass through value be less than or equal to it -- if you are setting both then why bother?  Not to mention that it is just a very confusing user interface to be presenting to people that don't know how this works in detail.

Pass through should only be used for setting parameters that are not explicitly enabled otherwise.  Of course the user can abuse it and set the value in both places but that should result in a potentially broken command invocation (the parameter specified multiple times).  The benchmark code should not be explicitly allowing the pass through parameter to override existing defined parameters as is done here:

https://github.com/perftool-incubator/bench-iperf/blob/main/iperf-client#L192-L200

And this doesn't even get into what conflicting parameters are going to do to parameter querying eventually...

**Comment by HughNhan** [comment]
The test length/time/duration enhancement was committed in https://github.com/perftool-incubator/bench-iperf/pull/17

**Comment by HughNhan** [comment]
Feature was add in https://github.com/perftool-incubator/bench-iperf/pull/17
